version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: tdrhq
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: |
             git fetch origin master
             sudo apt-get update
             sudo apt-get install -y imagemagick
             ./gen.sh
      - run:
          name: Fetch screenshotbot
          command: |
            curl https://screenshotbot.io/recorder.sh | sh
          when: always
      - run:
          name: Run affected tests
          command: |
            ./run-all-tests.sh
